### ISSUE TITLE
Secret Sharing between n Parties

### ISSUE THREAD

**Issue by mominbuet** [sharemind-sdk/build-sdk#1]
Hi,

I was going through the modules documentation in http://sharemind-sdk.github.io/stdlib/reference/modules.html

Is there any module for _n_ parties on the secret sharing? Also how do I define the IP address/setup parameters of these parties?

**Comment by karulont** [comment]
Hi,

At the moment we do not offer _n_ party modules.

As for the IP address setup: this is the SDK for developing applications. The Sharemind deployment configuration with cryptographic keys and IP addresses are not needed for developing applications for Sharemind.

The SDK contains the emulator, which emulates Sharemind, but on a single computer without actually providing any security. For trying the real thing, you can check on https://sharemind.cyber.ee/.

**Comment by mominbuet** [comment]
Thanks a lot
