### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by thanosgn** [sharemind-sdk/build-sdk#2]
Hello, after building the sdk according to the instructions I face a problem when trying to compile a sample SecreC file.

More specifically, when I run 
`./scc helloworld.sc` 
I get the followin error
`./scc: error while loading shared libraries: libscc.so.2.0: cannot open shared object file: No such file or directory`

I should note that libscc.so.2.0 exists in `prefix/lib` directory.

Any ideas?

//My operating system is Ubuntu 16.04.03 LTS

Thanks in advance.

**Comment by druid** [comment]
Hi!

Thank you for your interest in Sharemind software.

Since `scc` is built locally, you need to manually provide path to its required shared libraries (.so files) with `LD_LIBRARY_PATH`. Assuming you are in `prefix/bin`, you can use
```
LD_LIBRARY_PATH=../lib ./scc helloworld.sc
```

**Comment by thanosgn** [comment]
Thank you for your help and the quick response, that solved the issue!
