### ISSUE TITLE
Binding for missing system call found & Failed to load program bytecode

### ISSUE THREAD

**Issue by jimouris** [sharemind-sdk/build-sdk#3]
Hello,

I have compiled successfully the following SecreC file:
```
import shared3p;
import stdlib;
domain pd_shared3p shared3p;

void main() {
    pd_shared3p uint64 [[1]] x = {1, 2, 3, 4};
}
```

When I execute `LD_LIBRARY_PATH=../lib ./sharemind-emulator -c path_to/shared3p_emu.cfg path_to/mytest.sb`

I get the following errors:
`Error 1 of 2: Binding for missing system call found!`
`Error 2 of 2: Failed to load program bytecode: path_to/mytest.sb`

Thanks in advance,
Dimitris

**Comment by karulont** [comment]
You are giving the wrong configuration file to the emulator, but the emulator just ignores unknown entities in the config file and does not complain about it. Later when loading the program bytecode, we have missing syscalls, because the shared3p_emu module, which implements the syscalls related to shared3p protection domain, was never loaded by the emulator.

We have an outdate example of the config file in [here](https://github.com/sharemind-sdk/emulator/blob/master/doc/emulator.cfg.example). But right now it contains an error since the format changed a little and we forgot to update the example.
Please try to use the following [configuration.](https://gist.github.com/karulont/1d6bb35e39b05587446123e00048b4b3) In addition to fixing the format change it also has a few additional modules loaded in.

**Comment by jimouris** [comment]
Thanks for the reply, but I am still having a similar error.

`Error 1 of 2: Module returned INVALID_MODULE_CONFIGURATION!`
`Error 2 of 2: Failed to initialize module: libsharemind_mod_tabledb.so`

After I commented out the 3 lines about the "Module tabledb" I get the following:
`Error 1 of 2: Module returned GENERAL_ERROR!`
`Error 2 of 2: Failed to start protection domain: pd_shared3p`

PS:  shared3p_emu.cfg contains:
```
[ProtectionDomain]
ModelEvaluatorConfiguration = path_to/shared3p_emu-models.cfg
```

**Comment by karulont** [comment]
I checked that the ExecutionModelEvaluator throws an exception that is not catched in the mod_shared3p_emu protection domain startup and that can result in a GENERAL_ERROR.

Also what is the contents of `shared3p_emu-models.cfg`?

**Comment by jimouris** [comment]
This is the `shared3p_emu-models.cfg` file https://github.com/sharemind-sdk/packer-sharemind-sdk/blob/master/sharemind-sdk/files/sdk/sharemind-config/sharemind/shared3p_emu-models.cfg

**Comment by karulont** [comment]
I forgot about that repo being available. I cloned this repo, built everything and downloaded the shared3p_emu-models.cfg from the packer-sharemind-sdk repo.

I put the configuration files into `prefix/bin` directory and my shared3p_emu.cfg looks like that:
```
[ProtectionDomain]
ModelEvaluatorConfiguration = %{CurrentFileDirectory}/shared3p_emu-models.cfg
```
I am certain that this is some kind of configuration error.

**Comment by jimouris** [comment]
Thanks for your time. I am not sure that I understand correctly if the above works for you. I followed the same steps and I got the same error.

**Comment by karulont** [comment]
Steps I did:

1. Clone build-sdk.git & build everything
2. `cd prefix/bin`
3. Download the models: `wget https://raw.githubusercontent.com/sharemind-sdk/packer-sharemind-sdk/master/sharemind-sdk/files/sdk/sharemind-config/sharemind/shared3p_emu-models.cfg`
4. Download the emulator config: `wget https://gist.github.com/karulont/1d6bb35e39b05587446123e00048b4b3/raw/415429ab97068002a46354399c6db74b605748fa/emulator.cfg`
5. Create shared3p_emu.cfg with the content as I sayed in my previous comment: `vim shared3p_emu.cfg`
6. Create the test script: Content from this thread: `vim test.sc`
7. Compile SecreC: `LD_LIBRARY_PATH=../lib/ ./scc test.sc -o test.sb`
8. Try to run it: `LD_LIBRARY_PATH=../lib/ ./sharemind-emulator -c emulator.cfg test.sb`
Output is:
```
Error 1 of 2: Module returned INVALID_MODULE_CONFIGURATION!
Error 2 of 2: Failed to initialize module: libsharemind_mod_tabledb.so
```
9. Comment out or remove mod_tabledb from emulator conf: `vim emulator.cfg`
10. Try again: `LD_LIBRARY_PATH=../lib/ ./sharemind-emulator -c emulator.cfg test.sb`
Output:
```
Process returned status: 0
```

So for me it works.

**Comment by jimouris** [comment]
It works for me too now.

Thank you very much for your help and have a nice day.
