### ISSUE TITLE
libaccesscontrolprocessfacility fails to build

### ISSUE THREAD

**Issue by marsella** [sharemind-sdk/build-sdk#4]
I'm trying to make from `build-sdk`, and it's pulling the `master` branch from the `libaccesscontrolprocessfacility` repository. This fails because there's no `CMakeLists.txt` file there (in fact, there's nothing but a LICENSE). 

It looks like `stable-0.1` is the correct branch to use.

**Comment by karulont** [comment]
This was a configuration issue.
For now the `master` and `stable-0.1` branches are the same and the build should work.
