### ISSUE TITLE
Failed to load access policy

### ISSUE THREAD

**Issue by jimouris** [sharemind-sdk/build-sdk#6]
Hello,

I have downloaded and built sharemind. Compiling works fine, but when I run a .sb file I get the following error:
```
Using SHAREMIND_INSTALL_PREFIX='/path-to-build-sdk/build-sdk/prefix'
Running: '/path-to-main/main_7da047b6-b21c-48be-abd6-545681ea9f33.sb'
Error 1 of 2: No valid configuration file found after trying paths "path-to-build-sdk/.config/sharemind/emulator-access-control.conf", "/etc/xdg/xdg-gnome-xorg/sharemind/emulator-access-control.conf", "/etc/xdg/sharemind/emulator-access-control.conf", "/etc/sharemind/emulator-access-control.conf"!
Error 2 of 2: Failed to load access policy!
```
I am using Ubuntu 18.04.1 LTS.

Thank you very much in advance,
Dimitris Mouris

**Comment by karulont** [comment]
Hi, after you have compiled you can find example configuration files under 
`prefix/share/doc/sharemind-emulator-1.3.0/`.  You can copy `emulator-access-control.conf.example` to `~/.config/sharemind/emulator-access-control.conf`. But then after that you also need to copy `prefix/bin/shared3p_emu.cfg` and `prefix/bin/shared3p_emu-models.cfg` to `~/.config/sharemind/`.

Alternatively you can edit the configuration files to place them into other directories.

**Comment by jimouris** [comment]
After copying the files I get a different error:
```
Error 1 of 2: No such node (AccessControl)
Error 2 of 2: Path not found in configuration!
```

Also, I am using sharemind-emulator-1.1.0

**Comment by pr11t** [comment]
Hi @jimouris 

> After copying the files I get a different error:
> 
> ```
> Error 1 of 2: No such node (AccessControl)
> Error 2 of 2: Path not found in configuration!
> ```

This error seems to indicate that the emulator.conf file is invalid. Please confirm that the following example configuration files have been copied to `~/config/.sharemind/` directory with the .example suffix removed.

prefix/share/doc/sharemind-emulator-1.3.0/emulator-access-control.conf.example
prefix/share/doc/sharemind-emulator-1.3.0/emulator.conf.example
prefix/bin/shared3p_emu.cfg
prefix/bin/shared3p_emu-models.cfg

> 
> Also, I am using sharemind-emulator-1.1.0

It should work mostly the same, but the latest version is 1.3 so you may want to consider using that instead.

**Comment by jimouris** [comment]
@pr11t Yes, I think I should move to that version.
